[package]
name = "rust-handson"
version = "0.1.0"
authors = ["yuki.yoshikawa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
